publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "https://icyseascolab.io"
canonifyurls = true
theme = ["hugo-shortcode-roneo-collection", "hugo-academic-group"]
title = "Icy Seas Co-Lab"
math = true
copyright = "&copy; Thomas Bryce Kelly, 2025 "
pygmentsOptions = "linenos=table"


[taxonomies]
category = "categories"
tag = "tags"


[params]
  description = "Icy Seas Co-Laboratory LLC"
  author = "Thomas Bryce Kelly"
  email = "tkelly@icyseascolab.io"
  address = "762 Lancaster Drive, Fairbanks, AK 99712"
  phone = "(844) ICY-SEAS"

  [[params.logo]]
    image = "favicon.png"
    link = "/"

  slogan = "Icy Seas Co-Laboratory LLC"
  slogan_text = "Oceanographic Research"

  [[params.slogan_columns]]
    title = "About"
    text =  "At Icy Seas Co-Laboratory LLC, we bring together science, technology, and collaboration to better understand our changing oceans. Founded in Fairbanks, Alaska, we specialize in oceanographic research, data-driven solutions, and scientific consulting."
    link = "/about"
    link_text = "Our Policies"
    weight = 1
  
  [[params.slogan_columns]]
    title = "Mission"
    text = "Our work bridges field observations, advanced computing, and clear communication—helping researchers, communities, and organizations make informed decisions in a rapidly shifting Arctic."
    link = "/mission"
    link_text = "Read more"
    weight = 2

  [[params.slogan_columns]]
    title = "Approach"
    text = "We combine environmental observational systems, modeling tools, and creativity to diagnose processes in the earth climate system. This work bridges both discplines and scales."
    link = "/approach"
    link_text = "Read more"
    weight = 3

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""
    count = 0

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 4
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "News"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 0
    str_all = "More Projects"
  
[params.docs]
    title = "docs"
    subtitle = ""
    count = 0
    str_all = "More docs"

  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Vacancies"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?



  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.
[menu]
  [[menu.main]]
      name = "Home"
      url = "/#top"
      weight = 1

  [[menu.main]]
      name = "Research"
      url = "/research"
      weight = 2

# Products and Services
 [[menu.main]]
      name = "Products & Services"
      weight = 3
      identifier = "sales"
      url = "/docs/services"


  [[menu.main]]
      name = "FixPoint"
      url = "/project/ngalter"
      weight = 3
      parent = "sales"

  [[menu.main]]
      name = "Other"
      url = "/project/ngalter"
      weight = 3
      parent = "sales"


  [[menu.main]]
      name = "Members"
      url = "/member"
      weight = 5

  [[menu.main]]
      name = "Documentation"
      url = "/docs"
      weight = 6
