# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Icy Seas Co-Lab"
license = "MIT"
licenselink = "https://github.com/biaslab/hugo-academic-group/blob/master/LICENSE.md"
description = "A simple theme for academic groups and research departments."
homepage = "https://github.com/biaslab/hugo-academic-group"
tags = ["academic", "research", "university"]
features = ["blog", "landing"]
min_version = 0.15

[author]
  name = "Thomas Bryce Kelly"
  homepage = "https://tkelly.org/"
